

# 190412 | model

#### 1:N

게시글 - 댓글

데이터베이스를 편하게 조작하기 위해 ORM 으로 하고있었음 object relative 

pk 로 중복되지 않는 유일한 값이니까 record를 구붐할 수 있는 보장된 값

pk를 

게시글에 정보를 넣으려고 하면, 1번글에 여러개를 리스트든 뭐든으로 넣어주어야하니까 그걸 pk 를 매개체로

속해있는 n 인 애가 pk  값을 가지고 있음

ORM특징 (object == class)

1번 글이 가지고 있는 댓글,제목을 보여줘 

1번글 comment_set 

<- 왜 붙일까? 1:N에서 여러개를 가지고 올거임(댓글이 0,1,multiple일수있으니)- 저 하나하나 object를 뭉터기로 

 그러니까 set이라고 표현하고

결과는 항상 queryset (뭉터기로 옴 일종의 리스트)으로 올거임

그래서 여러개로 묶여이쓰니까 for을 돌려서 하나씩 꺼내와야하는거임 .content 식으로

board = models.FoeignKey(Board,) --- 얘를 N에 넣었겠지

하나만 가지고올거면 board라고 씀

댓글.board (1개) - 리턴값이 board의 object임



#### !! 내가 가지고오려는게 한개인지 여러개인지 확인하고

board = Board.objcets.get(pk=board_pk) return- object <- pk 값으로만 가져올 수 있고, 여러개면 오류, 없어도 오류 // 그래서 unique한 값만 가져오기위해 사용/ 하나만 딱/ object를 바로 가져올 수 있게

board = Board.objects.filter(title='111') return- queryset / 없읈도 하나일수도 있는데 리스트로 가져옴

filter - 이 column중에서 성이라고 하는 컬럼에서 김인 사람만 다 뽑아오기



#### get_object_or_404

board = get_object_or_404(Board, pk=board_pk) <- 리턴값없으면 오류 안뜨게 하려고 대신에 404를 띄워줘

- 인자는 Board (pk=board_pk) 말 안해주면 못가져오니까, 모델을 말해줘야하고, 그중에서 하나를 가져와야하니까 pk를 쓰는거고



어떻게 저 views의  import를 외울것인가?

ex 내가 로그인을 시킬거야 -> 그럼 import login,logout을 하겠지?

폼은 어딨어? ---- 로그인의 폼에 있어 

모델 윗  from django.db import models

from django import forms







CRUD MODELFORM

```django
oliviaspark0825:~/workspace $ mkdir morning
oliviaspark0825:~/workspace $ cd morning
oliviaspark0825:~/workspace/morning $ pyenv virtualenv 3.6.7 morning-venv
Looking in links: /tmp/tmpwu69_2hw
Requirement already satisfied: setuptools in /home/ubuntu/.pyenv/versions/3.6.7/envs/morning-venv/lib/python3.6/site-packages (39.0.1)
Requirement already satisfied: pip in /home/ubuntu/.pyenv/versions/3.6.7/envs/morning-venv/lib/python3.6/site-packages (10.0.1)
oliviaspark0825:~/workspace/morning $ pyenv local norning-venv
pyenv: version `norning-venv' not installed
oliviaspark0825:~/workspace/morning $ pyenv local morning-venv
(morning-venv) oliviaspark0825:~/workspace/morning $ pip install --upgrade pip
Collecting pip
  Using cached https://files.pythonhosted.org/packages/d8/f3/413bab4ff08e1fc4828dfc59996d721917df8e8583ea85385d51125dceff/pip-19.0.3-py2.py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 10.0.1
    Uninstalling pip-10.0.1:
      Successfully uninstalled pip-10.0.1
Successfully installed pip-19.0.3
(morning-venv) oliviaspark0825:~/workspace/morning $ python manage.py startapp posts
python: can't open file 'manage.py': [Errno 2] No such file or directory
(morning-venv) oliviaspark0825:~/workspace/morning $ pip install django==2.1.8
Collecting django==2.1.8
  Using cached https://files.pythonhosted.org/packages/a9/e4/fb8f473fe8ee659859cb712e25222243bbd55ece7c319301eeb60ccddc46/Django-2.1.8-py3-none-any.whl
Collecting pytz (from django==2.1.8)
  Using cached https://files.pythonhosted.org/packages/3d/73/fe30c2daaaa0713420d0382b16fbb761409f532c56bdcc514bf7b6262bb6/pytz-2019.1-py2.py3-none-any.whl
Installing collected packages: pytz, django
Successfully installed django-2.1.8 pytz-2019.1
(morning-venv) oliviaspark0825:~/workspace/morning $ pip list
Package    Version
---------- -------
Django     2.1.8  
pip        19.0.3 
pytz       2019.1 
setuptools 39.0.1 
(morning-venv) oliviaspark0825:~/workspace/morning $ django-admin startproject morning .
(morning-venv) oliviaspark0825:~/workspace/morning $ python manage.py startapp posts
(morning-venv) oliviaspark0825:~/workspace/morning $ pthon manage.py runserver 0.0.0.0:8080
bash: pthon: command not found
(morning-venv) oliviaspark0825:~/workspace/morning $ python manage.py runserver 0.0.0.0:8080                                                                                        
Performing system checks...

System check identified no issues (0 silenced).

You have 15 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.

April 11, 2019 - 23:22:54
Django version 2.1.8, using settings 'morning.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
python manage.py migrate
^C(morning-venv) oliviaspark0825:~/workspace/morning $ python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying sessions.0001_initial... OK
(morning-venv) oliviaspark0825:~/workspace/morning $ python manage.py makemigrations
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/.pyenv/versions/morning-venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/.pyenv/versions/morning-venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/home/ubuntu/.pyenv/versions/morning-venv/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/ubuntu/.pyenv/versions/morning-venv/lib/python3.6/site-packages/django/apps/registry.py", line 89, in populate
    app_config = AppConfig.create(entry)
  File "/home/ubuntu/.pyenv/versions/morning-venv/lib/python3.6/site-packages/django/apps/config.py", line 116, in create
    mod = import_module(mod_path)
  File "/home/ubuntu/.pyenv/versions/3.6.7/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'posts.aps'
(morning-venv) oliviaspark0825:~/workspace/morning $ python manage.py makemigrations
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/.pyenv/versions/morning-venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/.pyenv/versions/morning-venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/.pyenv/versions/morning-venv/lib/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/.pyenv/versions/morning-venv/lib/python3.6/site-packages/django/core/management/base.py", line 350, in execute
    self.check()
  File "/home/ubuntu/.pyenv/versions/morning-venv/lib/python3.6/site-packages/django/core/management/base.py", line 379, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/ubuntu/.pyenv/versions/morning-venv/lib/python3.6/site-packages/django/core/management/base.py", line 366, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/ubuntu/.pyenv/versions/morning-venv/lib/python3.6/site-packages/django/core/checks/registry.py", line 71, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/ubuntu/.pyenv/versions/morning-venv/lib/python3.6/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/home/ubuntu/.pyenv/versions/morning-venv/lib/python3.6/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/home/ubuntu/.pyenv/versions/morning-venv/lib/python3.6/site-packages/django/urls/resolvers.py", line 396, in check
    for pattern in self.url_patterns:
  File "/home/ubuntu/.pyenv/versions/morning-venv/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/ubuntu/.pyenv/versions/morning-venv/lib/python3.6/site-packages/django/urls/resolvers.py", line 533, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/ubuntu/.pyenv/versions/morning-venv/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/ubuntu/.pyenv/versions/morning-venv/lib/python3.6/site-packages/django/urls/resolvers.py", line 526, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/ubuntu/.pyenv/versions/3.6.7/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/workspace/morning/morning/urls.py", line 20, in <module>
    path('posts/', include('posts.urls')),
  File "/home/ubuntu/.pyenv/versions/morning-venv/lib/python3.6/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/ubuntu/.pyenv/versions/3.6.7/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/workspace/morning/posts/urls.py", line 1, in <module>
    from django.urls import paths
ImportError: cannot import name 'paths'
(morning-venv) oliviaspark0825:~/workspace/morning $ python manage.py makemigrations
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/.pyenv/versions/morning-venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/.pyenv/versions/morning-venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/.pyenv/versions/morning-venv/lib/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/.pyenv/versions/morning-venv/lib/python3.6/site-packages/django/core/management/base.py", line 350, in execute
    self.check()
  File "/home/ubuntu/.pyenv/versions/morning-venv/lib/python3.6/site-packages/django/core/management/base.py", line 379, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/ubuntu/.pyenv/versions/morning-venv/lib/python3.6/site-packages/django/core/management/base.py", line 366, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/ubuntu/.pyenv/versions/morning-venv/lib/python3.6/site-packages/django/core/checks/registry.py", line 71, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/ubuntu/.pyenv/versions/morning-venv/lib/python3.6/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/home/ubuntu/.pyenv/versions/morning-venv/lib/python3.6/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/home/ubuntu/.pyenv/versions/morning-venv/lib/python3.6/site-packages/django/urls/resolvers.py", line 396, in check
    for pattern in self.url_patterns:
  File "/home/ubuntu/.pyenv/versions/morning-venv/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/ubuntu/.pyenv/versions/morning-venv/lib/python3.6/site-packages/django/urls/resolvers.py", line 533, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/ubuntu/.pyenv/versions/morning-venv/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/ubuntu/.pyenv/versions/morning-venv/lib/python3.6/site-packages/django/urls/resolvers.py", line 526, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/ubuntu/.pyenv/versions/3.6.7/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/workspace/morning/morning/urls.py", line 20, in <module>
    path('posts/', include('posts.urls')),
  File "/home/ubuntu/.pyenv/versions/morning-venv/lib/python3.6/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/ubuntu/.pyenv/versions/3.6.7/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/workspace/morning/posts/urls.py", line 8, in <module>
    path('new/', views.create, name='create'),
AttributeError: module 'posts.views' has no attribute 'create'
(morning-venv) oliviaspark0825:~/workspace/morning $ python manage.py makemigrations
Migrations for 'posts':
  posts/migrations/0001_initial.py
    - Create model Post
(morning-venv) oliviaspark0825:~/workspace/morning $ python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, posts, sessions
Running migrations:
  Applying posts.0001_initial... OK
```

